name: Deploy Production

on:
  push:
    branches:
      - main

concurrency:
  group: production
  cancel-in-progress: true

jobs:
  deploy:
    runs-on:
      - self-hosted

    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Show Environment
        run: |
          whoami
          hostname
          pwd
          docker --version
          docker compose version

      - name: Pull Public Images
        run: |
          docker compose pull prometheus

      - name: Build Application
        run: |
          docker compose build api

      - name: Deploy
        run: |
          docker compose up -d

      - name: Cleanup
        run: |
          docker image prune -f

      - name: Health Check
        run: |
          sleep 10
          curl --fail http://localhost:8000/health